### ISSUE TITLE
Oops, an error occurred!

### ISSUE THREAD

**Issue by arunspt** [bingquan3846/templavoila2fluid#1]
Hi,

I installed this extension in my TYPO3 6.2.27 installation to convert templavoila to fluid. When I click on the backend module "Templavoila to fluid", it leads to an error like this;

"Oops, an error occurred!
Could not analyse class:TYPO3\CMS\Backend\View\BackendTemplateView maybe not loaded or no autoloader?"

![error](https://cloud.githubusercontent.com/assets/20816321/18806300/5b123232-8246-11e6-9450-1dac6eabf22c.png)

Please help me to solve the issue.

Thanks,
Arun

**Comment by bingquan3846** [comment]
Hallo,
sorry, download the latest code  from repository,  it should work in typo3 6.2.27. 
Best luck. :)

**Comment by arunspt** [comment]
Hi,
Thank you. I'll check this.
